"""Write sirefs.tex: the numbers that the Supporting Information gives to the tables and figures that the main text cites.

Reads the label numbers from si.aux (run tectonic on si.tex first) and writes one macro per label, for example
\\siTabWt{} -> S12 for the label tab:wt. A label that is missing prints S? so that the gap is visible in the PDF.
"""
from __future__ import annotations

import re
from pathlib import Path

here = Path(__file__).parent
LABELS = {
    "tab:data": "siTabData", "tab:main": "siTabMain", "tab:wt": "siTabWt",
    "fig:main": "siFigMain", "fig:response": "siFigResponse", "fig:levels": "siFigLevels", "fig:scale": "siFigScale", "fig:scan": "siFigScan", "fig:wt": "siFigWt",
}
aux = (here / "si.aux").read_text(encoding="utf-8", errors="ignore") if (here / "si.aux").exists() else ""
found = dict(re.findall(r"\\newlabel\{([^}]+)\}\{\{([^}]*)\}", aux))
lines = ["% generated by make_sirefs.py from si.aux"]
for lab, mac in LABELS.items():
    lines.append("\\newcommand{\\%s}{%s}" % (mac, found.get(lab, "S?")))
(here / "sirefs.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
print({m: found.get(l, "S?") for l, m in LABELS.items()})
